services:

  backend:
    build:
      context: ./api
    container_name: api
    # ports are no longer required exposing because NGINX exposes only port 80
    # ports:
    #   - "8000:8000"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    # environment:
    #   - DATABASE_URL=postgresql+asyncpg://swagato:ranDom1234@database:5432/  # database:5432 -- database is the service name
    env_file:
      - ./api/.env

  database:
    image: postgres:18
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

      # You can peek inside the postgres container with: docker exec -it postgres_db psql -U swagato -d mypgdb

  seed:
    build:
      context: ./api
    depends_on:
      database:
        condition: service_healthy
    command: python -m scripts.seed
    env_file:
      - ./api/.env
    profiles:
      - tools

    # Run the seed service with: docker compose --profile tools run --rm seed or, docker compose --profile tools up seed

  celery_worker:
    build:
      context: ./api
    container_name: celery_worker
    command: celery -A app.celery_app.celery_app worker --loglevel=info -Q default
    depends_on:
      - backend
      - redis
      - database
    env_file:
      - ./api/.env
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s #1m30s
      timeout: 3s
      retries: 5
      start_period: 10s

    # See if the redis container is working: docker exec -it redis redis-cli ping  <-- redis is the container name. You should get a PONG response.

  flower:
    build:
      context: ./api
    container_name: celery_flower
    command: >
      celery -A app.celery_app.celery_app flower
      --port=5555
      --url_prefix=flower
      --basic_auth=admin:Password123
    # Remove the ports section. Instead, route it through nginx like /flower.
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker
    env_file:
      - ./api/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./my-demo
    container_name: frontend
    # NGINX exposes only port 80
    # ports:
    #   - "3000:3000"
    environment:
      - PUBLIC_API_URL=/api
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"
  #   restart: unless-stopped

volumes:
  pg_data:
  redis_data: