"""Add table TranscodedUploadSession, TranscodedUploadFile

Revision ID: 0b5dcf785c13
Revises: 18a5a4f44642
Create Date: 2026-10-02 09:11:41.262430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5dcf785c13'
down_revision: Union[str, Sequence[str], None] = '18a5a4f44642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcoded_upload_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADING', 'PAUSED', 'COMPLETED', 'FAILED', 'ABORTED', name='transcodeduploadstatusenum'), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('uploaded_files_count', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('transcoded_upload_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transcoded_upload_session_id', sa.UUID(), nullable=False),
    sa.Column('client_file_id', sa.String(length=64), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transcoded_upload_session_id'], ['transcoded_upload_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcoded_upload_session_id', 'relative_path', name='uq_transcoded_upload_file_path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcoded_upload_files')
    op.drop_table('transcoded_upload_sessions')
    # ### end Alembic commands ###
