"""VideoEvent.transcode_task_id -> nullable

Revision ID: 290389758cff
Revises: 6ded7943423b
Create Date: 2026-07-04 18:53:02.130198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '290389758cff'
down_revision: Union[str, Sequence[str], None] = '6ded7943423b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_events', 'transcode_task_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_events', 'transcode_task_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
