"""Rename: processing_events -> video_events

Revision ID: 63e122973d62
Revises: 1a8b6a098cee
Create Date: 2026-06-23 20:40:17.726806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63e122973d62'
down_revision: Union[str, Sequence[str], None] = '1a8b6a098cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transcode_task_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcode_task_id'], ['transcode_tasks.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('processing_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transcode_task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['transcode_task_id'], ['transcode_tasks.id'], name=op.f('processing_events_transcode_task_id_fkey')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('processing_events_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('processing_events_pkey'))
    )
    op.drop_table('video_events')
    # ### end Alembic commands ###
