"""RENAME: TranscodeTask.job_external_id -> task_id

Revision ID: 6ded7943423b
Revises: e57a83ae7ee9
Create Date: 2026-07-01 23:22:28.656631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ded7943423b'
down_revision: Union[str, Sequence[str], None] = 'e57a83ae7ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcode_tasks', sa.Column('task_id', sa.String(length=255), nullable=True))
    op.drop_column('transcode_tasks', 'job_external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcode_tasks', sa.Column('job_external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('transcode_tasks', 'task_id')
    # ### end Alembic commands ###
