"""Removed upload_session from TranscodeTask model

Revision ID: 7a26f04ae911
Revises: 050f78fb8699
Create Date: 2026-08-05 19:44:46.270934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a26f04ae911'
down_revision: Union[str, Sequence[str], None] = '050f78fb8699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transcode_tasks', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('transcode_tasks_upload_session_id_fkey'), 'transcode_tasks', type_='foreignkey')
    op.drop_column('transcode_tasks', 'upload_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcode_tasks', sa.Column('upload_session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('transcode_tasks_upload_session_id_fkey'), 'transcode_tasks', 'upload_sessions', ['upload_session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('transcode_tasks', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
