"""UploadSession object_key, video_upload_id, file_size_bytes, mime_type, original_filename, uploaded_parts_count -> nullable=True

Revision ID: 7a3e206aecae
Revises: bf991883dd9d
Create Date: 2026-07-05 16:43:59.915002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3e206aecae'
down_revision: Union[str, Sequence[str], None] = 'bf991883dd9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_sessions', 'object_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('upload_sessions', 'video_upload_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('upload_sessions', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('upload_sessions', 'mime_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('upload_sessions', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('upload_sessions', 'uploaded_parts_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_sessions', 'uploaded_parts_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('upload_sessions', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('upload_sessions', 'mime_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('upload_sessions', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('upload_sessions', 'video_upload_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('upload_sessions', 'object_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
