"""Series.videos added passive_deletes=True

Revision ID: 7aebb2af59d7
Revises: ff57450a496f
Create Date: 2026-07-30 18:04:38.544563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aebb2af59d7'
down_revision: Union[str, Sequence[str], None] = 'ff57450a496f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
