"""Canged status field and its enum in Video model

Revision ID: 7ef68a7f7eff
Revises: 63e122973d62
Create Date: 2026-06-24 14:50:09.194609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ef68a7f7eff'
down_revision: Union[str, Sequence[str], None] = '63e122973d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# custom modification: enum.create()
publication_status_enum = postgresql.ENUM("DRAFT", "PUBLISHED", "ARCHIVED", name="videopublicationstatusenum")

old_status_enum = postgresql.ENUM(
    "IDLE",
    "FAILED",
    "ABORTED",
    "COMPLETED",
    "UPLOADING",
    "PAUSED",
    name="videostatusenum"
)

def upgrade() -> None:
    """Upgrade schema."""

    # custom modification:
    publication_status_enum.create(
        op.get_bind(),
        checkfirst=True
    )

    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('videos', sa.Column('publication_status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='videopublicationstatusenum'), nullable=False))
    
    # custom
    op.add_column('videos', sa.Column('publication_status', publication_status_enum, nullable=False, server_default="DRAFT"))
    
    op.drop_column('videos', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # custom
    old_status_enum.create(
        op.get_bind(),
        checkfirst=True
    )

    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('videos', sa.Column('status', postgresql.ENUM('IDLE', 'FAILED', 'ABORTED', 'COMPLETED', 'UPLOADING', 'PAUSED', name='videostatusenum'), autoincrement=False, nullable=False))
    
    # custom
    op.add_column("videos", sa.Column("status", old_status_enum, nullable=False, server_default="IDLE"))
    
    op.drop_column('videos', 'publication_status')
    # ### end Alembic commands ###

    # custom
    publication_status_enum.drop(
        op.get_bind(),
        checkfirst=True
    )