"""video.video_object_storage_prefix not required

Revision ID: 8065c9bd80c2
Revises: 7ef68a7f7eff
Create Date: 2026-06-24 20:09:02.210257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8065c9bd80c2'
down_revision: Union[str, Sequence[str], None] = '7ef68a7f7eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'publication_status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='videopublicationstatusenum'),
               server_default=None,
               existing_nullable=False)
    op.drop_column('videos', 'video_object_storage_prefix')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video_object_storage_prefix', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('videos', 'publication_status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='videopublicationstatusenum'),
               server_default=sa.text("'DRAFT'::videopublicationstatusenum"),
               existing_nullable=False)
    # ### end Alembic commands ###
