"""UploadSession.total_parts -> nullable

Revision ID: bf991883dd9d
Revises: 5d3f9bb8c17d
Create Date: 2026-07-04 19:10:00.432698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf991883dd9d'
down_revision: Union[str, Sequence[str], None] = '5d3f9bb8c17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_sessions', 'total_parts',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_sessions', 'total_parts',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
