"""ADD: rlationship among Video and TranscodedUploadSession

Revision ID: ccf6168b096e
Revises: 0b5dcf785c13
Create Date: 2026-10-05 13:55:09.636776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf6168b096e'
down_revision: Union[str, Sequence[str], None] = '0b5dcf785c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
