"""set nullable=True for UploadSession.video_id

Revision ID: d7360220d579
Revises: 8065c9bd80c2
Create Date: 2026-06-24 23:04:59.644653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7360220d579'
down_revision: Union[str, Sequence[str], None] = '8065c9bd80c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_sessions', 'video_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_sessions', 'video_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
