"""Removed Video.transcript

Revision ID: db8c150e5f58
Revises: 7aebb2af59d7
Create Date: 2026-08-04 19:38:50.648618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8c150e5f58'
down_revision: Union[str, Sequence[str], None] = '7aebb2af59d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'transcript')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
