"""Video update

Revision ID: e57a83ae7ee9
Revises: d7360220d579
Create Date: 2026-06-25 00:28:10.064083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e57a83ae7ee9'
down_revision: Union[str, Sequence[str], None] = 'd7360220d579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('videos', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('videos', 'language',
               existing_type=postgresql.ENUM('HINDI', 'BENGALI', name='languageenum'),
               nullable=True)
    op.alter_column('videos', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('videos', 'language',
               existing_type=postgresql.ENUM('HINDI', 'BENGALI', name='languageenum'),
               nullable=False)
    op.alter_column('videos', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('videos', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
