"""create upload sessions

Revision ID: e602aa5f3a3f
Revises: 59dd9f6a7ee1
Create Date: 2026-07-07 18:19:00.471112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e602aa5f3a3f'
down_revision: Union[str, Sequence[str], None] = '59dd9f6a7ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=True),
    sa.Column('object_key', sa.String(length=255), nullable=True),
    sa.Column('video_upload_id', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('total_parts', sa.Integer(), nullable=True),
    sa.Column('uploaded_parts_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'uploading', 'paused', 'completed', 'failed', 'aborted', name='uploadsessionstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'transcode_tasks', 'upload_sessions', ['upload_session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'upload_parts', 'upload_sessions', ['upload_session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upload_parts', type_='foreignkey')
    op.drop_constraint(None, 'transcode_tasks', type_='foreignkey')
    op.drop_table('upload_sessions')
    # ### end Alembic commands ###
