"""UploadSessionStatusEnum IDLE -> PENDING

Revision ID: ed2d8430fdda
Revises: 7a3e206aecae
Create Date: 2026-07-05 16:50:19.861146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2d8430fdda'
down_revision: Union[str, Sequence[str], None] = '7a3e206aecae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
