"""Video.thumbnail_object_storage_prefix -> thumbnail_object_key. New Field: UploadSession.completed_at

Revision ID: ff57450a496f
Revises: 4c5e5b386099
Create Date: 2026-07-27 23:35:01.842012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff57450a496f'
down_revision: Union[str, Sequence[str], None] = '4c5e5b386099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_sessions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('videos', sa.Column('thumbnail_object_key', sa.String(length=255), nullable=True))
    op.drop_column('videos', 'thumbnail_object_storage_prefix')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumbnail_object_storage_prefix', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('videos', 'thumbnail_object_key')
    op.drop_column('upload_sessions', 'completed_at')
    # ### end Alembic commands ###
